dist: trusty

os:
- linux

language: go

go:
- "1.11"
- tip

install:
- go get github.com/mattn/goveralls
- go get github.com/lawrencewoodman/roveralls
- go get github.com/golang/dep/cmd/dep
- dep ensure -vendor-only

script:
- roveralls
- goveralls -coverprofile=roveralls.coverprofile -service=travis-ci
