dist: trusty

os:
- linux

language: go

go:
- "1.15"
- tip

env:
- GO111MODULE=on

install:
- go get github.com/mfridman/tparse
- go get github.com/mattn/goveralls
- go get github.com/lawrencewoodman/roveralls

script:
- make check
- make coveralls
